on:
  push:
    tags:
      - 'smart-contract-verifier/v*'
    paths:
      - smart-contract-verifier/**
      - .github/workflows/smart-contract-verifier.yml

name: Docker (smart-contract-verifier)

defaults:
  run:
    working-directory: smart-contract-verifier

jobs:
  push:
    name: Docker build and docker push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex
        with:
          text: ${{ github.ref }}
          regex: '^(refs\/tags\/smart-contract-verifier\/(v\d+\.\d+\.\d+))|(refs\/heads\/(main))$'

      - name: Extract tag name
        id: tags_extractor
        run: |
          t=${{ steps.regex.outputs.group2 }}
          m=${{ steps.regex.outputs.group4 }}
          (if ! [[ "$t" == "" ]]; then echo tags=gulabs/gu-blockscout-smart-contract-verifier:$t, gulabs/gu-blockscout-smart-contract-verifier:latest; elif ! [[ "$m" == "" ]]; then echo tags=gulabs/gu-blockscout-smart-contract-verifier:$m; else echo tags=; fi) >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gulabs/gu-blockscout-smart-contract-verifier

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "smart-contract-verifier"
          file: "smart-contract-verifier/smart-contract-verifier-server/Dockerfile"
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: ${{ steps.tags_extractor.outputs.tags != '' }}
          tags: ${{ steps.tags_extractor.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
