on:
  push:
    tags:
      - 'stats/v*'
    paths:
      - stats/**
      - .github/workflows/stats.yml

name: Docker (stats)

defaults:
  run:
    working-directory: stats

jobs:
  push:
    name: Docker build and docker push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/stats/(.*)$'

      - name: Extract tag name
        id: tags_extractor
        run: |
          t=${{ steps.regex.outputs.group1 }}
          if [[ ! -z "$t" ]]; then
            echo tags=gulabs/gu-blockscout-stats:$t, gulabs/gu-blockscout-stats:latest >> $GITHUB_OUTPUT
          else
            echo tags= >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gulabs/gu-blockscout-stats

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "stats"
          file: "stats/Dockerfile"
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: ${{ steps.tags_extractor.outputs.tags != '' }}
          tags: ${{ steps.tags_extractor.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
